/* SevenBeat — offline browser demo. AudioContext is the only playback clock. */
'use strict';
const $=id=>document.getElementById(id),A=window.SEVEN_ASSETS,{Engine,validateChart}=SevenBeatCore;
const copy=x=>JSON.parse(JSON.stringify(x)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const defaults={keys:['KeyD','KeyJ'],latency:0,speed:640,volume:75,hitSound:true,sfxVolume:65,voiceEnabled:true,voiceVolume:80,skinScales:{},menuEnabled:true,menuSong:'sympathy',menuVolume:35,colorShapes:{...SevenColors.defaults},laneColors:['cyan','pink'],effects:true,comboGlow:true,palette:'night',scene:'campus',ambient:'auto',ambientAmount:65,ambientEnabled:true,elastic:75};
let settings=copy(defaults);try{Object.assign(settings,JSON.parse(localStorage.getItem('sevenbeat-settings')||'{}'));}catch{}
settings.skinScales=settings.skinScales&&typeof settings.skinScales==='object'&&!Array.isArray(settings.skinScales)?settings.skinScales:{};
settings.voiceVolume=clamp(Number(settings.voiceVolume)||0,0,100);
let reactions=null,ending=null,decorImages={},colorSprites={};
settings.colorShapes={...SevenColors.defaults,...(settings.colorShapes||{})};settings.laneColors=Array.isArray(settings.laneColors)?settings.laneColors:['cyan','pink'];
const exampleAudio=item=>item.audio||A.examples[item.audioKey]?.audio;
const firstExample=A.examples.tutorial;
let chart=validateChart(firstExample.chart),audioData=firstExample.audio,audioName=firstExample.chart.audio,buffer=null,view='play',status='ready',engine=null;
let ctx=null,source=null,musicGain=null,sfxGain=null,mixGain=null,recordAudio=null,anchor=0,position=0,clockRunning=false,decodeToken=0;
let practice=false,practiceStart=0,renderTime=0,selected=null,tool='tap',scroll=0,zoom=110,undoStack=[],redoStack=[],drag=null,noteRecording=[null,null];
let customSkins={},images={},action={kind:'run',lane:1,until:0,grade:''},particles=[],judgements=[],impacts=[],targetHits=[null,null],bindLane=null,calibration=null;
let dirty=false,lastHud=0,toastTimer,bootReady=false,activePointers=new Map(),physicalKeys=new Set(),skinLoadToken=0;
// Position belongs to input state. Note judgements may change the pose, never the lane.
const characterInput={held:[false,false],lastLane:1,airUntil:0,autoReleaseAt:[0,0]};
function resetCharacterInput(){document.querySelectorAll('.is-down').forEach(el=>el.classList.remove('is-down'));characterInput.held=[false,false];characterInput.lastLane=1;characterInput.airUntil=0;characterInput.autoReleaseAt=[0,0];if(typeof visualMotion!=='undefined'){visualMotion.y=472;visualMotion.vy=0;visualMotion.squash=0;visualMotion.vs=0;}}
function pressCharacter(lane,now=performance.now()){const input=characterInput;if(input.held[lane])return;const anchored=input.held[1-lane];input.held[lane]=true;if(!anchored){input.lastLane=lane;input.airUntil=lane===0?now+180:0;}visualMotion.vs+=anchored?-.65:lane===0?-2.7:2.3;}
function releaseCharacter(lane){const input=characterInput;if(!input.held[lane])return;input.held[lane]=false;input.autoReleaseAt[lane]=0;if(input.lastLane===lane&&input.held[1-lane]){input.lastLane=1-lane;input.airUntil=input.lastLane===0?performance.now()+180:0;}}
function characterLane(now=performance.now()){const input=characterInput;if(input.held[input.lastLane])return input.lastLane;if(input.held[1-input.lastLane])return 1-input.lastLane;return input.lastLane===0&&now<input.airUntil?0:1;}
function crossPose(){return characterInput.held[0]&&characterInput.held[1]?(characterInput.lastLane===0?'downslash':'upslash'):null;}
function characterPose(now=performance.now()){const cross=crossPose();if(cross)return cross;const lane=characterLane(now),active=characterInput.held[lane]&&engine?.notes.some(n=>n.state==='holding'&&n.lane===lane);return active?'hold':now<action.until?action.kind:'run';}
// Auto mode may resequence its simulated keys to establish an air anchor before a hazard.
function autoJump(now,until){const ground=characterInput.held[1],releaseAt=characterInput.autoReleaseAt[1];if(ground&&characterInput.lastLane===1){releaseCharacter(1);pressCharacter(0,now);pressCharacter(1,now);characterInput.autoReleaseAt[1]=releaseAt;}else pressCharacter(0,now);characterInput.autoReleaseAt[0]=engine?.notes.some(n=>n.lane===0&&n.state==='holding')?0:Math.max(characterInput.autoReleaseAt[0],until);}
const game=$('game'),timeline=$('timeline'),tg=timeline.getContext('2d');
let g=game.getContext('2d');
document.body.classList.toggle('touch-device',navigator.maxTouchPoints>0||matchMedia('(any-pointer:coarse)').matches);
const visualMotion={y:472,vy:0,squash:0,vs:0,last:0};
const recording=new SevenRecorder({onState:updateRecordingState,onReady:recordingReady,onError:e=>toast(e.message)});
const timeText=(t,ms=false)=>{t=Math.max(0,t);return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}${ms?'.'+String(Math.floor((t%1)*1000)).padStart(3,'0'):''}`;};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200);}
function saveSettings(){try{localStorage.setItem('sevenbeat-settings',JSON.stringify(settings));}catch{toast('浏览器未允许保存设置，本次会话仍然有效。');}}
function ensureContext(){if(!ctx){ctx=new (window.AudioContext||window.webkitAudioContext)({latencyHint:'interactive'});musicGain=ctx.createGain();sfxGain=ctx.createGain();mixGain=ctx.createGain();recordAudio=ctx.createMediaStreamDestination();musicGain.connect(mixGain);sfxGain.connect(mixGain);sfxGain.gain.value=settings.sfxVolume/100;mixGain.connect(ctx.destination);mixGain.connect(recordAudio);musicGain.gain.value=settings.volume/100;reactions=new SevenReactions.AudioReactions(ctx,musicGain,mixGain,sfxGain,()=>settings);}return ctx;}
function dataBytes(uri){const s=atob(uri.split(',')[1]),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a.buffer;}
async function decodeAudio(data){const token=++decodeToken;const decoded=await ensureContext().decodeAudioData(dataBytes(data));if(token!==decodeToken)return false;buffer=decoded;return true;}
function clockTime(){return clockRunning?ctx.currentTime-anchor:position;}
function stopClock(){if(clockRunning)position=clockTime();clockRunning=false;resumeUntil=0;if(source){source.onended=null;try{source.stop();}catch{}source.disconnect();source=null;}}
async function startClock(at=0){if(!buffer)throw new Error('音频尚未准备好，请稍后再试。');await ensureContext().resume();stopClock();position=at;anchor=ctx.currentTime-at;source=ctx.createBufferSource();source.buffer=buffer;source.connect(musicGain);source.start(ctx.currentTime+Math.max(0,-at),Math.max(0,at));clockRunning=true;}
function songTime(){return clockTime()-chart.offset-settings.latency/1000;}
function duration(){return buffer?.duration||chart.duration||178;}
function clickTone(lane=0,when=null,cal=false,grade='PERFECT'){if(!ctx||(!cal&&(!settings.hitSound||settings.sfxVolume<=0)))return;const at=when??ctx.currentTime,bus=cal?mixGain:sfxGain;for(let i=0;i<(cal?1:2);i++){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=cal?'sine':i?'sine':'triangle';const freq=cal?1000:grade==='GOOD'?(lane?540:720):(lane?760:1040);osc.frequency.setValueAtTime(freq*(i?1.5:1),at);osc.frequency.exponentialRampToValueAtTime(freq*(i?.7:.45),at+.065);gain.gain.setValueAtTime(cal?.16:i?.065:.11,at);gain.gain.exponentialRampToValueAtTime(.0001,at+.085);osc.connect(gain);gain.connect(bus);osc.start(at);osc.stop(at+.09);osc.onended=()=>{osc.disconnect();gain.disconnect();};}}
function syncDodgeInput(){if(!engine||engine.auto)return;const now=performance.now(),air=characterLane(now)===0,t=songTime(),until=air&&characterInput.held[0]?Infinity:t+Math.max(0,characterInput.airUntil-now)/1000;engine.setAirborne(air,t,until);}
function judge({note,grade,error}){const now=performance.now(),dodge=note.type==='dodge';
 if(grade==='DODGE_READY'){autoJump(now,now+Math.max(0,note.time-songTime())*1000+120);return;}
 if(grade!=='MISS')clickTone(dodge?0:note.lane,null,false,grade);
 if(engine?.auto){if(dodge){autoJump(now,now+120);}else if(grade==='HOLD'||(note.type==='tap'&&grade!=='MISS')){pressCharacter(note.lane,now);characterInput.autoReleaseAt[note.lane]=note.type==='tap'?now+80:0;}else if(note.type==='hold')releaseCharacter(note.lane);}
 action={kind:grade==='MISS'?'miss':grade==='GOOD'?'good':grade==='HOLD'?'hold':characterLane(now)===0?'upper':'lower',lane:characterLane(now),until:now+270,grade};const feedback={text:grade,grade,error,lane:note.lane,dodge,born:now};judgements=judgements.filter(j=>j.lane!==feedback.lane||j.dodge!==feedback.dodge);judgements.push(feedback);impacts.push(feedback);targetHits[note.lane]=feedback;if(judgements.length>8)judgements.shift();}
function setStatus(s){status=s;syncMenuMusic();$('modeBadge').textContent=({ready:'准备就绪',loading:'正在准备音频',playing:engine?.auto?'AUTO · 自动演示':practice?'PRACTICE · 练习':'LIVE · 游玩中',paused:'PAUSED · 已暂停',finished:'TRACK COMPLETE'})[s];$('playPause').textContent=s==='playing'?'Ⅱ 暂停':s==='paused'?'▶ 继续':'▶ 开始';$('stagePause').textContent=s==='playing'?'Ⅱ':'▶';document.querySelector('.stage-shell').dataset.state=s;document.body.dataset.gameState=s;}
async function startGame(at=0){try{reactions?.stop();ending=null;setStatus('loading');await ensureContext().resume();if(!buffer)await decodeAudio(audioData);chart=validateChart(chart);engine=new Engine(chart,judge);engine.auto=$('autoplay').checked;practice=at>0;practiceStart=at;engine.seekPractice(Math.max(0,at-chart.offset-settings.latency/1000));physicalKeys.clear();activePointers.clear();resetCharacterInput();particles=[];judgements=[];impacts=[];targetHits=[null,null];action={kind:'run',lane:1,until:0,grade:''};$('overlay').classList.add('hidden');$('result').classList.add('hidden');await startClock(at-1.5);setStatus('playing');if(document.body.classList.contains('touch-device')&&!document.fullscreenElement&&!document.body.classList.contains('stage-expanded'))game.scrollIntoView({block:'center'});reactions.play(Math.random()<.5?'start-1':'start-2');}catch(e){setStatus('ready');toast(e.message);}}
function pauseGame(){if(status!=='playing')return;reactions?.stop();stopClock();setStatus('paused');physicalKeys.clear();activePointers.clear();resetCharacterInput();engine.held=[false,false];engine.setAirborne(false,songTime());$('overlay').innerHTML='<div class="overlay-card"><span class="eyebrow">TAKE A BREATH</span><h2>节拍等你回来。</h2><p>继续后有 1 秒缓冲 · 正在长按的音符需要重新按住</p><button id="resumeOverlay" class="primary">继续游玩 ↗</button></div>';$('overlay').classList.remove('hidden');$('resumeOverlay').onclick=resumeGame;}
let resumeUntil=0;
async function resumeGame(){if(status!=='paused')return;await ctx.resume();const p=position;anchor=ctx.currentTime-p+1;source=ctx.createBufferSource();source.buffer=buffer;source.connect(musicGain);source.start(ctx.currentTime+1+Math.max(0,-p),Math.max(0,p));clockRunning=false;resumeUntil=performance.now()+1000;setStatus('playing');$('overlay').classList.add('hidden');}
function resetOverlay(){$('overlay').innerHTML='<div class="overlay-card"><span class="eyebrow">READY WHEN YOU ARE</span><h2>让每一击，都合拍。</h2><p>怪兽抵达光圈时击打 · 长条按住 · 地面齿轮跳起躲开</p><button id="startOverlay" class="primary">开始游玩 <span>↗</span></button><div class="key-guide"><span><kbd class="upperKey"></kbd> 空中轨道</span><span><kbd class="lowerKey"></kbd> 地面轨道</span></div></div>';$('startOverlay').onclick=()=>startGame();updateKeyLabels();}
function exitGame(){reactions?.stop();ending=null;if(recording.active)recording.stop();stopClock();resumeUntil=0;position=0;engine=null;practice=false;physicalKeys.clear();activePointers.clear();resetCharacterInput();setStatus('ready');resetOverlay();$('overlay').classList.remove('hidden');$('result').classList.add('hidden');updateHUD();}
function finishGame(){if(status==='finished')return;stopClock();setStatus('finished');reactions.stop();const outcome=SevenReactions.outcome(engine.counts,chart.notes.length,{practice,auto:engine.auto}),acc=engine.accuracy,rank=acc>=98?'S':acc>=90?'A':acc>=75?'B':'C',voiceKey=outcome.judged?SevenReactions.chooseVoice(outcome.hitRate):null;ending={...outcome,born:performance.now(),voiceKey};const celebration=outcome.fullCombo?reactions.celebrate():0,speech=voiceKey?reactions.play(voiceKey,outcome.fullCombo?.65:0):0;ending.until=ending.born+Math.max(outcome.fullCombo?5500:1200,celebration*1000,speech*1000+350);const friend=outcome.fullCombo||outcome.hitRate>80?'cheer':outcome.hitRate>=60?'tea':'shrug';$('result').innerHTML=`<div class="overlay-card result-card ${outcome.fullCombo?'is-full-combo':''}"><span class="eyebrow">${engine.auto?'AUTO PLAY · 演示结果':practice?'PRACTICE · 练习结果':'TRACK COMPLETE · 完成'}</span>${outcome.fullCombo?'<h2 class="full-combo-title">FULL COMBO!</h2><p class="fc-subtitle">零失误通关！每一拍，都接住了 ♡</p>':`<div class="result-grade">${rank}</div>`}<img class="ui-friend result-friend" src="${imageURL(decorImages[friend])}" alt="" aria-hidden="true"><div class="result-score">${String(engine.score).padStart(7,'0')}</div><div class="result-stats"><span>${outcome.hitRate.toFixed(2)}%<small>命中率</small></span><span>${acc.toFixed(2)}%<small>准确率</small></span><span>${engine.maxCombo}<small>最高连击</small></span><span>${engine.counts.PERFECT} / ${engine.counts.GOOD} / ${engine.counts.MISS}<small>PERFECT / GOOD / MISS</small></span></div><div class="result-buttons"><button id="againResult" class="primary">再来一次 ↗</button><button id="editResult">调整谱面</button></div></div>`;$('result').classList.remove('hidden');$('againResult').onclick=()=>startGame(practiceStart);$('editResult').onclick=()=>switchView('editor');}
function switchView(v){if(v!=='play')reactions?.stop();if(v!=='play'&&recording.active)recording.stop();if(view==='play'&&status==='playing')pauseGame();if(view==='editor'){stopClock();noteRecording=[null,null];}if(v==='editor'&&engine)exitGame();if(calibration&&v!=='settings')endCalibration();view=v;document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===v));document.querySelectorAll('.nav').forEach(el=>el.classList.toggle('active',el.dataset.view===v));if(v==='editor'){position=clamp(position,0,duration());syncEditor();}if(v==='settings')refreshSettings();}
function keyName(code){return code.startsWith('Key')?code.slice(3):code.startsWith('Digit')?code.slice(5):code.replace('Arrow','↑↓←→'[['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].indexOf(code)]||'');}
function updateKeyLabels(){document.querySelectorAll('.upperKey').forEach(el=>el.textContent=keyName(settings.keys[0]));document.querySelectorAll('.lowerKey').forEach(el=>el.textContent=keyName(settings.keys[1]));$('bindUpper').textContent=keyName(settings.keys[0]);$('bindLower').textContent=keyName(settings.keys[1]);$('recordNotes').parentElement.lastChild.textContent=` 实时录入 ${keyName(settings.keys[0])} / ${keyName(settings.keys[1])}`;}
function hit(lane){if(status!=='playing'||engine.auto||characterInput.held[lane])return;pressCharacter(lane);syncDodgeInput();if(resumeUntil){engine.held[lane]=true;return;}action={kind:characterLane()?'lower':'upper',lane,until:performance.now()+180,grade:''};engine.press(lane,songTime());}
function release(lane){if(status==='playing'&&!engine.auto){releaseCharacter(lane);syncDodgeInput();if(resumeUntil)engine.held[lane]=false;else engine.release(lane,songTime());}}
function updateHUD(){$('stageScore').textContent='SCORE '+String(engine?.score||0).padStart(7,'0');$('score').textContent=String(engine?.score||0).padStart(7,'0');$('accuracy').textContent=(engine?.accuracy??100).toFixed(2)+'%';$('maxCombo').textContent=engine?.maxCombo||0;for(const [id,k]of[['perfectCount','PERFECT'],['goodCount','GOOD'],['missCount','MISS']])$(id).textContent=engine?.counts[k]||0;$('timeLabel').textContent=timeText(Math.max(0,clockTime()))+' / '+timeText(duration());$('progressBar').style.width=clamp(clockTime()/duration()*100,0,100)+'%';updateTutorialUI();}
function syncSong(){$('songTitle').textContent=chart.title;$('songArtist').textContent=chart.artist;$('noteTotal').textContent=chart.notes.filter(n=>n.type!=='dodge').length;$('gearTotal').textContent=chart.notes.filter(n=>n.type==='dodge').length;$('holdTotal').textContent=chart.notes.filter(n=>n.type==='hold').length;$('durationTotal').textContent=timeText(duration());const kind=chart.source?.kind;$('songTag').textContent=kind==='tutorial'?'TUTORIAL':kind==='original-kawaii'?'KAWAII BASS':kind==='video-reconstruction'?(chart.source.difficulty==='easy'?'EASY · 简单':'STANDARD · 标准'):'CHART';$('songSource').textContent=kind==='tutorial'?'60 秒 · 原创 120 BPM 配乐。逐步学习短按、长按、齿轮和交叉击打。':kind==='original-kawaii'?'120 秒 · 150 BPM · 350 节拍。主歌四分音符、高潮八分音符；随乐句切换配色。':kind==='video-reconstruction'?chart.source.difficulty==='easy'?`${chart.bpm} BPM · 简单模式：减少连打，长按与齿轮前后留白。沿用标准谱面的落点与乐句配色。`:`${chart.bpm} BPM · 标准模式。连续短按间隔整理，配色按乐句统一。`:'可按时间轴编辑节奏、图案和颜色，导出时保留设置。';const built=Object.entries(A.examples).find(([key,item])=>item.chart.audio===chart.audio&&item.chart.title===chart.title);$('builtinChart').value=built?built[0]:'';const base=built?.[0]?.replace(/_easy$/,'');$('difficultyBar').classList.toggle('hidden',!A.examples[base+'_easy']);document.querySelectorAll('[data-difficulty]').forEach(b=>{b.disabled=loadingExample;b.classList.toggle('selected',b.dataset.difficulty===(built?.[0]?.endsWith('_easy')?'easy':'standard'));b.setAttribute('aria-pressed',String(b.classList.contains('selected')));});document.querySelectorAll('[data-song]').forEach(b=>{const chosen=base===b.dataset.song;b.classList.toggle('selected',chosen);b.setAttribute('aria-pressed',String(chosen));});if(status==='ready'&&$('startOverlay'))$('startOverlay').firstChild.textContent=kind==='tutorial'?'开始教程 ':'开始游玩 ';}

let loadingExample=false;
async function loadBuiltIn(key){if(loadingExample)return;const item=A.examples?.[key];if(!item){toast('没有找到这份内置谱面。');return;}loadingExample=true;$('loadBuiltIn').disabled=true;document.querySelectorAll('[data-song],[data-difficulty]').forEach(b=>b.disabled=true);try{if(recording.active)await recording.stop();exitGame();stopClock();await decodeAudio(exampleAudio(item));checkpoint();chart=validateChart(item.chart);audioData=exampleAudio(item);audioName=chart.audio;position=0;scroll=0;selected=null;changed();syncEditor();updateHUD();$('builtinChart').value=key;toast(`${chart.title} 已载入，点击开始即可游玩。`);}catch(e){toast('载入失败：'+e.message);}finally{loadingExample=false;$('loadBuiltIn').disabled=false;document.querySelectorAll('[data-song],[data-difficulty]').forEach(b=>b.disabled=false);}}

// Image rendering: a flood fill removes only white regions touching the edge of supplied default sprites.
function loadImage(url){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('贴图无法读取。'));im.src=url;});}
function cutWhite(im){const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0);const d=x.getImageData(0,0,c.width,c.height),p=d.data,w=c.width,h=c.height,visited=new Uint8Array(w*h),q=new Int32Array(w*h);let head=0,tail=0;const add=i=>{if(i<0||i>=w*h||visited[i])return;visited[i]=1;const j=i*4;if(p[j]>233&&p[j+1]>233&&p[j+2]>233){q[tail++]=i;p[j+3]=0;}};for(let xx=0;xx<w;xx++){add(xx);add((h-1)*w+xx);}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1);}while(head<tail){const i=q[head++];if(i%w)add(i-1);if(i%w<w-1)add(i+1);add(i-w);add(i+w);}x.putImageData(d,0,0);return c;}
const charDefaults={run:'run',upper:'upper',lower:'lower',hold:'dash',good:'lower',miss:'portrait',upslash:'upslash',downslash:'downslash'};
async function loadSkins(){const token=++skinLoadToken;const next={};await Promise.all([...Object.keys(charDefaults),...Object.keys(A.skins),'background'].map(async key=>{let url=customSkins[key]||(charDefaults[key]?A.characters[charDefaults[key]]:A.skins[key]);if(!url)return;const im=await loadImage(url);next[key]=!customSkins[key]&&charDefaults[key]&&key!=='miss'?cutWhite(im):im;}));if(token!==skinLoadToken)return;images=next;refreshSkinSlots();}
function imageURL(im){return im instanceof HTMLCanvasElement?im.toDataURL():im?.src;}
function refreshSkinSlots(){const worlds=[['background','循环背景'],['upperNote','空中怪兽'],['lowerNote','地面怪兽'],['obstacle','滚动齿轮 / 闪避'],['holdNote','长按头部']];const sourceKey={upperNote:'upper',lowerNote:'lower',holdNote:'hold'};
 $('worldSkins').replaceChildren();for(const[key,label]of worlds){const b=document.createElement('button');b.className='skin-slot';b.dataset.skin=key;const im=images[key]||(!sourceKey[key]?images[key]:null);const src=customSkins[key]||A.skins[sourceKey[key]||key];if(src){const p=document.createElement('img');p.src=src;p.alt=label;b.append(p);}else{const sw=document.createElement('div');sw.className='swatch';sw.textContent='☾';b.append(sw);}const span=document.createElement('span');span.textContent=label;const small=document.createElement('small');small.textContent=`推荐 ${SevenAssetEditor.recommended(key).join(' × ')} · ${Math.round(assetScale(key)*100)}%`; span.append(small);b.append(span);b.onclick=()=>chooseSkin(key);$('worldSkins').append(b);}
 $('characterSkins').replaceChildren();for(const[key,label]of Object.entries({run:'跑步 / 待机',upper:'空中 PERFECT',lower:'地面 PERFECT',hold:'长按 / 冲刺',good:'GOOD / 挥刀',miss:'MISS / 受击',upslash:'上撩 / 地面交叉击打',downslash:'下劈 / 空中交叉击打'})){const b=document.createElement('button');b.className='skin-slot';b.dataset.skin=key;const p=document.createElement('img');p.src=imageURL(images[key]);p.alt=label;const s=document.createElement('span');s.textContent=label;const small=document.createElement('small');small.textContent=`推荐 768 × 768 · ${Math.round(assetScale(key)*100)}%`;s.append(small);b.append(p,s);b.onclick=()=>chooseSkin(key);$('characterSkins').append(b);}}
function chooseSkin(key){assetEditor.open(key,skinLabels[key]||key).catch(e=>toast(e.message));}

// Canvas scene: original vector scenery, two scrolling parallax layers and original monster sprites.
function ellipse(x,y,rx,ry,fill){g.fillStyle=fill;g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fill();}
function roundRect(x,y,w,h,r,fill){g.fillStyle=fill;g.beginPath();g.roundRect(x,y,w,h,r);g.fill();}
function textAt(s,x,y,size,color,weight='500',align='left',outline=0){g.font=`${weight} ${size}px "SevenCute","Segoe UI","Microsoft YaHei",sans-serif`;g.fillStyle=color;g.textAlign=align;if(outline){g.save();g.strokeStyle='#52485e';g.lineWidth=outline;g.lineJoin='round';g.strokeText(s,x,y);g.restore();}g.fillText(s,x,y);}
function comboShining(){return !!(settings.comboGlow&&engine&&engine.combo>10&&(status==='playing'||status==='paused'));}
const glowMasks=new WeakMap();
function glowMask(im){if(glowMasks.has(im))return glowMasks.get(im);const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);x.globalCompositeOperation='source-in';x.fillStyle='#fff9cf';x.fillRect(0,0,c.width,c.height);glowMasks.set(im,c);return c;}
function drawComboAura(t,front=false){if(!comboShining())return;g.save();const y=visualMotion.y-40,pulse=.5+.5*Math.sin(t*4.2);if(!front){const glow=g.createRadialGradient(181,y,25,181,y,153);glow.addColorStop(0,'#fff2bd45');glow.addColorStop(.55,'#ffd78324');glow.addColorStop(1,'#ffe5a300');g.fillStyle=glow;g.beginPath();g.ellipse(181,y,153,164,0,0,Math.PI*2);g.fill();g.strokeStyle=`rgba(255,231,166,${.23+pulse*.12})`;g.lineWidth=2;g.beginPath();g.ellipse(181,y,109+pulse*6,127+pulse*7,-.13,0,Math.PI*2);g.stroke();}for(let i=0;i<10;i++){if((i%2===0)!==front)continue;const phase=t*.7+i*2.399,x=181+Math.cos(phase)*(85+i%3*15),yy=y+Math.sin(phase)*(105+i%3*13),r=3.5+(.5+.5*Math.sin(t*3+i))*4;g.globalAlpha=.42+.45*(.5+.5*Math.sin(t*2.8+i));g.shadowColor='#ffd77b';g.shadowBlur=9;g.fillStyle=i%3?'#fff5ce':'#fff';g.beginPath();g.moveTo(x,yy-r*1.5);g.lineTo(x+r*.35,yy-r*.3);g.lineTo(x+r,yy);g.lineTo(x+r*.35,yy+r*.3);g.lineTo(x,yy+r*1.5);g.lineTo(x-r*.35,yy+r*.3);g.lineTo(x-r,yy);g.lineTo(x-r*.35,yy-r*.3);g.closePath();g.fill();}g.restore();}
function noteSprite(n){const custom=n.type==='hold'?images.holdNote:n.lane?images.lowerNote:images.upperNote;if(custom)return custom;return colorSprites[SevenColors.color(n,settings)+':'+SevenColors.shape(n,settings)]||(n.lane?images.noteLower:images.noteUpper);}
function drawScene(now,showUI=true){const t=status==='ready'?now/1000:clockTime();
 const theme=SevenWorlds.draw(g,t,settings.scene,settings.customBackground!==false?images.background||null:null,assetScale('background'));
 if(settings.ambientEnabled)SevenWorlds.ambient(g,t,settings.scene,settings.ambient,settings.ambientAmount,false);
 const lanes=[285,475],colors=['#2bdde9','#ff4fad'];for(let l=0;showUI&&l<2;l++){const y=lanes[l];g.strokeStyle=colors[l]+'55';g.lineWidth=3;g.setLineDash([10,12]);g.beginPath();g.moveTo(380,y);g.lineTo(1280,y);g.stroke();g.setLineDash([]);SevenComic.target(g,l,y,t,keyName(settings.keys[l]),!!engine?.held[l]&&status==='playing',targetHits[l],settings.effects);}
 const acting=now<action.until,kind=characterPose(now),im=images[kind]||images.run;
 drawComboAura(t);
 if(im){const h=(kind==='miss'?205:240)*assetScale(kind),w=h*im.width/im.height,bob=Math.sin(t*17)*3,power=settings.elastic/100,stretch=clamp(visualMotion.squash,-.19,.18)*power;ellipse(173,555,91-(472-visualMotion.y)*.14,16-(472-visualMotion.y)*.035,'#25213940');g.save();g.translate(181+(acting?Math.sin((now-action.until)*.07)*4*power:0),visualMotion.y+35+bob);if(kind==='miss'){g.globalAlpha=.7;g.rotate(-.1);}else if(kind!=='downslash')g.scale(-1,1);g.scale(1+stretch,1-stretch);g.rotate(clamp(visualMotion.vy*.00013,-.12,.12)*power+(kind==='good'?.05:0));if(comboShining()){g.shadowColor='#ffe4a3';g.shadowBlur=17+7*Math.sin(t*4.2);}g.drawImage(im,-w/2,-h*.63,w,h);if(comboShining()){g.shadowBlur=0;g.globalAlpha=.08+.07*(.5+.5*Math.sin(t*4.2));g.drawImage(glowMask(im),-w/2,-h*.63,w,h);}g.restore();}
 drawComboAura(t,true);
 if(acting&&action.grade!=='MISS'&&settings.effects){g.save();g.translate(270,lanes[action.lane]);g.strokeStyle=action.lane?'#ffd4edaa':'#caffdfaa';g.lineWidth=9;g.beginPath();g.arc(0,0,88,-1.1,.75);g.stroke();g.restore();}
 if(engine&&status!=='ready'){const st=songTime();for(const n of engine.notes){if(n.state==='done'&&(n.type!=='dodge'||n.grade!=='PERFECT'))continue;const dodge=n.type==='dodge',x=(dodge?181:330)+(n.time-st)*settings.speed,endX=x+n.duration*settings.speed;if(n.time-st>(1430-181)/settings.speed)break;if(x>1430)continue;if(endX<-100)continue;if(dodge){SevenComic.gear(g,n,x,t,images.obstacle,showUI,assetScale('obstacle'));continue;}const y=lanes[n.lane],color=SevenColors.palettes[SevenColors.color(n,settings)].main;if(n.type==='hold'){const start=n.state==='holding'?330:x;roundRect(start,y-19,Math.max(1,endX-start),38,13,'#261c42');roundRect(start+3,y-14,Math.max(1,endX-start-6),28,10,color);ellipse(endX,y,16,23,'#251d42');ellipse(endX,y,11,18,'#fff065');for(let xx=start+23;xx<endX;xx+=42)textAt('›',xx,y+8,24,'#fff','800','center',2);}const sprite=noteSprite(n);SevenComic.note(g,n,n.state==='holding'?330:x,y,t,sprite,settings.elastic/100,assetScale(n.type==='hold'?'holdNote':n.lane?'lowerNote':'upperNote'));}}
 else if(status==='ready'){for(let l=0;l<2;l++)for(let i=0;i<4;i++){const n={id:'preview-'+l+'-'+i,type:'tap',lane:l,skin:'monster'},x=630+i*230+(l?100:0)-(t*45)%230;SevenComic.note(g,n,x,lanes[l],t,noteSprite(n),settings.elastic/100,assetScale(l?'lowerNote':'upperNote'));}}
 if(settings.ambientEnabled)SevenWorlds.ambient(g,t,settings.scene,settings.ambient,settings.ambientAmount,true);
 if(showUI&&engine&&status!=='ready'){g.save();g.translate(1150,126);const pop=1+Math.max(0,action.until-now)/230*.12*settings.elastic/100;g.scale(pop,pop);g.shadowColor='#53496488';g.shadowBlur=5;textAt(String(engine.combo),0,0,58,'#fff9e9','800','center',3);g.shadowBlur=0;textAt('COMBO',0,25,12,'#fff9e9','700','center',2);g.restore();}
 judgements=judgements.filter(j=>now-j.born<780);for(const j of judgements)SevenComic.feedback(g,j,now,showUI);impacts=impacts.filter(j=>now-j.born<600);if(settings.effects)for(const j of impacts)SevenComic.impact(g,j,now);
 if(showUI&&status!=='finished')SevenLesson.draw(g,currentLesson(),crossPose());
 SevenReactions.drawCelebration(g,ending,now,{ui:showUI,effects:settings.effects});
 if(showUI&&status==='playing'&&(clockTime()<0||resumeUntil>now)){const count=resumeUntil>now?'READY':String(Math.ceil(-clockTime()));textAt(count,670,340,75,'#effff3','800','center',4);}
}

function currentLesson(){return SevenLesson.current(chart,status==='ready'?0:Math.min(songTime(),Math.max(0,duration()-.05)),settings.keys.map(keyName));}
function updateTutorialUI(){const lesson=currentLesson(),coach=$('tutorialCoach');coach.classList.toggle('hidden',!lesson);if(!lesson)return;const title=lesson.title,body=lesson.lines.join(' ');if($('lessonTitle').textContent!==title)$('lessonTitle').textContent=title;if($('lessonText').textContent!==body)$('lessonText').textContent=body;$('lessonStep').textContent=`${lesson.index+1} / ${lesson.total}`;const pose=crossPose();$('lessonPose').textContent=pose==='downslash'?'下劈 · 保持空中':pose==='upslash'?'上撩 · 保持地面':`先按住的键决定高度 · ${keyName(settings.keys[0])} 空中 / ${keyName(settings.keys[1])} 地面`;}

// Editor uses a view window; no giant canvases even for long imported songs.
function checkpoint(){undoStack.push(copy(chart));if(undoStack.length>100)undoStack.shift();redoStack=[];dirty=true;}
function changed(){chart.notes.sort((a,b)=>a.time-b.time||a.lane-b.lane);dirty=true;syncSong();$('editorNoteCount').textContent=chart.notes.length+' NOTES';$('saveStatus').textContent='有未保存的修改';}
function syncEditor(){$('chartTitle').value=chart.title;$('bpm').value=chart.bpm;$('chartOffset').value=chart.offset;$('audioName').textContent=audioName;$('timelineScroll').max=duration();$('editorNoteCount').textContent=chart.notes.length+' NOTES';updateInspector();syncSong();}
function editorSnap(t){const division=Number($('snap').value);return Math.max(0,division?Math.round(t/(60/chart.bpm/division))*(60/chart.bpm/division):t);}
function eventPoint(e){const r=timeline.getBoundingClientRect(),x=(e.clientX-r.left)*timeline.width/r.width,y=(e.clientY-r.top)*timeline.height/r.height;return{x,y,time:Math.max(0,scroll+(x-85)/zoom),lane:y<178?0:1};}
function findNote(p){let best=null,bestDist=Infinity;for(const n of chart.notes){if(n.lane!==p.lane)continue;const x=85+(n.time-scroll)*zoom,end=x+n.duration*zoom,dist=Math.abs(x-p.x);if(p.x>=x-9&&p.x<=end+10&&dist<bestDist){best=n;bestDist=dist;}}return best;}
function addNote(t,lane,type='tap',len=0){const n={id:'n-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),time:Math.round(t*10000)/10000,lane:type==='dodge'?1:lane,type,duration:type==='hold'?Math.max(.08,len):0,skin:type==='dodge'?'obstacle':'monster',color:'lane'};const draft=copy(chart);draft.notes.push(n);try{validateChart(draft);}catch(e){toast(e.message);return null;}chart.notes.push(n);selected=n.id;changed();updateInspector();return n;}
function drawTimeline(){const r=timeline.getBoundingClientRect();if(r.width>0&&timeline.width!==Math.round(r.width)){timeline.width=Math.round(r.width);}const w=timeline.width;tg.fillStyle='#131723';tg.fillRect(0,0,w,280);tg.font='11px SevenCute, monospace';tg.fillStyle='#242838';tg.fillRect(85,36,w-85,56);
 if(buffer){const samples=buffer.getChannelData(0),sr=buffer.sampleRate;tg.strokeStyle='#a6f7d466';tg.lineWidth=1;tg.beginPath();for(let x=85;x<w;x+=2){const t=scroll+(x-85)/zoom,start=Math.max(0,Math.floor((t+chart.offset)*sr)),step=Math.max(1,Math.floor(sr/zoom*2/10));let max=0;for(let j=0;j<10;j++)max=Math.max(max,Math.abs(samples[start+j*step]||0));tg.moveTo(x,64-max*24);tg.lineTo(x,64+max*24);}tg.stroke();}
 const div=Number($('snap').value)||4,beat=60/chart.bpm,step=beat/div;let drawStep=step;while(drawStep*zoom<9)drawStep*=2;for(let t=Math.floor(scroll/drawStep)*drawStep;t<scroll+(w-85)/zoom;t+=drawStep){const x=85+(t-scroll)*zoom;if(x<85)continue;const major=Math.abs(t/beat-Math.round(t/beat))<.001;tg.strokeStyle=major?'#454657':'#252938';tg.beginPath();tg.moveTo(x,major?25:94);tg.lineTo(x,266);tg.stroke();if(major&&beat*zoom>28){tg.fillStyle='#8c97ab';tg.fillText(t.toFixed(2),x+3,19);}}
 tg.fillStyle='#a6f7d407';tg.fillRect(85,97,w-85,75);tg.fillStyle='#e1baff07';tg.fillRect(85,181,w-85,75);for(const n of chart.notes){const x=85+(n.time-scroll)*zoom;if(x>w+15)break;const end=x+n.duration*zoom;if(end<85)continue;const y=n.lane?218:134;tg.fillStyle=SevenColors.palettes[SevenColors.color(n,settings)].main;if(n.type==='hold'){tg.globalAlpha=.45;tg.fillRect(Math.max(85,x),y-11,Math.max(0,end-Math.max(85,x)),22);tg.globalAlpha=1;tg.fillRect(end-3,y-16,6,32);}tg.beginPath();if(n.type==='dodge'){tg.fillStyle='#ffcf36';for(let i=0;i<24;i++){const a=i*Math.PI/12,r=i%2?10:15;i?tg.lineTo(x+Math.cos(a)*r,y+Math.sin(a)*r):tg.moveTo(x+Math.cos(a)*r,y+Math.sin(a)*r);}tg.closePath();}else tg.roundRect(x-8,y-15,16,30,5);tg.fill();if(n.id===selected){tg.strokeStyle='#ffffff';tg.lineWidth=2;tg.strokeRect(x-12,y-20,Math.max(24,n.duration*zoom+24),40);}}
 if(drag?.newNote){const x=85+(drag.start-scroll)*zoom,end=85+(drag.current-scroll)*zoom,y=drag.lane?218:134;tg.fillStyle='#fff5';tg.fillRect(Math.min(x,end),y-14,Math.abs(end-x)||16,28);}
 tg.fillStyle='#191d2b';tg.fillRect(0,0,85,280);tg.fillStyle='#a6f7d4';tg.fillText('AIR  / '+keyName(settings.keys[0]),12,138);tg.fillStyle='#dbb4f5';tg.fillText('LAND / '+keyName(settings.keys[1]),12,222);tg.fillStyle='#8490a8';tg.fillText('AUDIO',12,67);
 const playhead=clockTime()-chart.offset,x=85+(playhead-scroll)*zoom;if(x>=85&&x<=w){tg.strokeStyle='#ffdd96';tg.lineWidth=2;tg.beginPath();tg.moveTo(x,27);tg.lineTo(x,265);tg.stroke();tg.fillStyle='#ffdd96';tg.beginPath();tg.moveTo(x-6,25);tg.lineTo(x+6,25);tg.lineTo(x,33);tg.fill();}if(clockRunning&&playhead>scroll+(w-150)/zoom){scroll=Math.max(0,playhead-.5);$('timelineScroll').value=scroll;}$('editorTime').textContent=timeText(clockTime(),true);$('previewAudio').textContent=clockRunning?'Ⅱ 暂停':'▶ 试听';}
function updateInspector(){const n=chart.notes.find(n=>n.id===selected);$('selectionLabel').textContent=n?`#${chart.notes.indexOf(n)+1}`:'未选择';for(const [id,k]of[['noteTime','time'],['noteLane','lane'],['noteType','type'],['noteDuration','duration'],['noteSkin','skin'],['noteColor','color']]){$(id).disabled=!n;$(id).value=n?n[k]:'';}$('applyNote').disabled=!n;$('deleteNote').disabled=!n;}
function deleteSelected(){if(!selected)return;checkpoint();chart.notes=chart.notes.filter(n=>n.id!==selected);selected=null;changed();updateInspector();}
timeline.onpointerdown=e=>{if(view!=='editor')return;const p=eventPoint(e);if(p.x<85)return;if(p.y<95){stopClock();position=clamp(p.time+chart.offset,0,duration());return;}const n=findNote(p);if(e.button===2||tool==='erase'){if(n){selected=n.id;deleteSelected();}return;}timeline.setPointerCapture(e.pointerId);if(n){selected=n.id;checkpoint();drag={id:n.id,original:copy(n),start:p.time,oldChart:copy(chart)};updateInspector();}else if(tool==='select'){selected=null;updateInspector();}else{drag={newNote:true,start:editorSnap(p.time),current:editorSnap(p.time),lane:p.lane,type:tool};}};
timeline.onpointermove=e=>{if(!drag)return;const p=eventPoint(e);if(drag.newNote)drag.current=editorSnap(p.time);else{const n=chart.notes.find(n=>n.id===drag.id);n.time=editorSnap(drag.original.time+p.time-drag.start);n.lane=n.type==='dodge'?1:p.lane;updateInspector();}};
function endDrag(){if(!drag)return;if(drag.newNote){checkpoint();const from=Math.min(drag.start,drag.current),len=Math.abs(drag.current-drag.start);addNote(from,drag.lane,drag.type,Math.max(60/chart.bpm/4,len));}else{try{validateChart(chart);}catch(e){chart=drag.oldChart;toast(e.message);}changed();}drag=null;updateInspector();}
timeline.onpointerup=endDrag;timeline.onpointercancel=()=>{if(drag&&!drag.newNote)chart=drag.oldChart;drag=null;updateInspector();};timeline.oncontextmenu=e=>e.preventDefault();timeline.onwheel=e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY>0?.9:1.1),35,400);$('zoom').value=zoom;};
function undo(){if(!undoStack.length)return;redoStack.push(copy(chart));chart=undoStack.pop();selected=null;changed();syncEditor();}
function redo(){if(!redoStack.length)return;undoStack.push(copy(chart));chart=redoStack.pop();selected=null;changed();syncEditor();}
function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),15000);}
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
function safeChart(){const c=validateChart(chart);const max=c.notes.reduce((m,n)=>Math.max(m,n.time+n.duration+c.offset),0);if(max>duration()+.1)throw new Error('部分音符超出歌曲结尾，请先调整时间或导入正确的歌曲。');c.duration=duration();c.audio=audioName;return c;}
async function exportChart(){try{const c=safeChart();if($('includeAudio').checked)c.audioData=audioData;download((c.title.replace(/[\\/:*?"<>|]/g,'_')||'chart')+'.json',JSON.stringify(c,null,2));dirty=false;$('saveStatus').textContent='已导出可读 JSON';toast('谱面已导出到浏览器下载目录。');}catch(e){toast(e.message);}}
let dbPromise=null;
function database(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('sevenbeat-demo',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return dbPromise;}
async function persist(key,value){const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
async function recall(key){const db=await database();return new Promise((resolve,reject)=>{const r=db.transaction('data').objectStore('data').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function saveProject(){try{const c=safeChart();await persist('project',{chart:c,audioData,audioName});dirty=false;$('saveStatus').textContent='已保存到本机';toast('已保存；下次打开会恢复这份谱面。');}catch(e){toast('保存失败：'+e.message+'。请使用导出 JSON。');}}

function refreshSettings(){refreshWorldSettings();refreshColorSettings();refreshMenuSettings();for(const id of['latency','speed','volume','sfxVolume','voiceVolume'])$(id).value=settings[id];for(const id of['hitSound','effects','comboGlow','voiceEnabled'])$(id).checked=settings[id];document.querySelectorAll('[data-palette]').forEach(b=>b.classList.toggle('selected',b.dataset.palette===settings.palette));updateKeyLabels();}
function calibrationTap(){if(!calibration)return;const elapsed=ctx.currentTime-calibration.first,index=Math.round(elapsed/.5);if(index>=2&&index<12&&index!==calibration.last&&Math.abs(elapsed-index*.5)<.24){calibration.last=index;calibration.diffs.push(elapsed-index*.5);$('calibrationStatus').textContent=`已记录 ${calibration.diffs.length} 拍…`;}}
function endCalibration(){if(!calibration)return;$('calibrationTap').classList.add('hidden');const diffs=calibration.diffs;calibration=null;$('calibrate').textContent='♪ 节拍校准：听 12 拍并跟拍';if(diffs.length>=4){diffs.sort((a,b)=>a-b);settings.latency=Math.round(clamp(diffs[Math.floor(diffs.length/2)]*1000,-500,500));saveSettings();refreshSettings();$('calibrationStatus').textContent=`已采集 ${diffs.length} 拍；延迟补偿设为 ${settings.latency>0?'+':''}${settings.latency} ms，可手动微调。`;}else $('calibrationStatus').textContent='有效击打不足 4 次；请重试或手动填写延迟。';}
async function startCalibration(){if(calibration){endCalibration();return;}await ensureContext().resume();const first=ctx.currentTime+1;calibration={first,index:0,diffs:[],last:-1,end:first+6};$('calibrationTap').classList.remove('hidden');$('calibrate').textContent='正在校准… 按空格或点下方按钮';$('calibrationStatus').textContent='听到声音就按空格或点一次「跟拍」；前两拍用于适应。';}

async function loadCuteFont(){if(!A.fontPackage)throw new Error('缺少封装字体，请重新生成素材包。');const packed=new Uint8Array(dataBytes(A.fontPackage));if(packed.length<10||String.fromCharCode(...packed.slice(0,4))!=='SBFP'||packed[4]!==1)throw new Error('字体封装格式无效。');const expected=new DataView(packed.buffer).getUint32(5),decoded=await new Response(new Blob([packed.slice(9)]).stream().pipeThrough(new DecompressionStream('deflate'))).arrayBuffer();if(decoded.byteLength!==expected||new DataView(decoded).getUint32(0)!==0x774f4646)throw new Error('字体封装校验失败。');const font=new FontFace('SevenCute',decoded,{style:'normal',weight:'400'});document.fonts.add(await font.load());await document.fonts.ready;}
function updateVisualMotion(now){const dt=visualMotion.last?clamp((now-visualMotion.last)/1000,0,.05):1/60;visualMotion.last=now;const target=characterLane(now)===0?290:472,power=clamp(settings.elastic/100,0,1);if(!power){visualMotion.y=target;visualMotion.vy=0;visualMotion.squash=0;visualMotion.vs=0;return;}if(status==='paused')return;for(let i=0;i<4;i++){const step=dt/4;visualMotion.vy+=((target-visualMotion.y)*780-visualMotion.vy*(46-17*power))*step;visualMotion.y+=visualMotion.vy*step;visualMotion.vs+=(-visualMotion.squash*190-visualMotion.vs*13)*step;visualMotion.squash+=visualMotion.vs*step;}visualMotion.y=clamp(visualMotion.y,275,491);}
function buildSceneChooser(){const names={petals:'花瓣',leaves:'枫叶',snow:'雪花',dust:'微尘',fireflies:'萤火'};$('sceneChooser').replaceChildren();for(const [key,theme]of Object.entries(SevenWorlds.themes)){const canvas=document.createElement('canvas');canvas.width=320;canvas.height=180;const c=canvas.getContext('2d');c.scale(.25,.25);SevenWorlds.draw(c,1,key);SevenWorlds.ambient(c,1,key,'auto',36,true);const button=document.createElement('button');button.className='scene-card';button.dataset.scene=key;const im=document.createElement('img');im.src=canvas.toDataURL();im.alt=theme.name;const label=document.createElement('span');label.textContent=theme.name;const small=document.createElement('small');small.textContent=names[theme.particle];label.append(small);button.append(im,label);button.onclick=()=>{settings.scene=key;settings.customBackground=false;saveSettings();refreshWorldSettings();};$('sceneChooser').append(button);}}
function refreshWorldSettings(){if(!SevenWorlds.themes[settings.scene])settings.scene='campus';settings.elastic=clamp(Number(settings.elastic)||0,0,100);settings.ambientAmount=clamp(Number(settings.ambientAmount)||0,0,130);for(const id of['elastic','ambientAmount'])$(id).value=settings[id];$('ambient').value=settings.ambient;$('ambientEnabled').checked=settings.ambientEnabled;$('elasticValue').textContent=settings.elastic+'%';document.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('selected',b.dataset.scene===settings.scene&&(!customSkins.background||settings.customBackground===false)));$('useCustomBackground').classList.toggle('hidden',!customSkins.background);document.querySelector('.stage-tag').textContent=customSkins.background&&settings.customBackground!==false?'YOUR LITTLE WORLD':SevenWorlds.themes[settings.scene].caption;}
function updateRecordingState(state){const busy=recording.active||state==='stopping';$('recordStart').disabled=busy||!SevenRecorder.mime();$('recordStop').disabled=!recording.active;$('recordUI').disabled=busy;$('recordFPS').disabled=busy;document.querySelector('.recording-toolbar').classList.toggle('is-recording',state==='recording');updateRecordingCounter();}
function updateRecordingCounter(){$('recordStatus').textContent=recording.state==='recording'?(status==='paused'?'REC 暂停画面 ':'REC ')+timeText(recording.seconds):recording.state==='preparing'?'正在准备编码器…':recording.state==='stopping'?'正在生成…':recording.result?'视频已就绪':'未录制';}
let lastRecordingFrame=0;
function paintRecording(now,force=false){if(!recording.active)return;const period=1000/recording.options.fps;if(!force&&now-lastRecordingFrame<period)return;lastRecordingFrame=force||!lastRecordingFrame?now:now-((now-lastRecordingFrame)%period);recording.paint((target,includeUI)=>{const visible=g;g=target;try{drawScene(now,includeUI);if(includeUI){drawRecordingHUD();if(status==='paused'){roundRect(475,294,330,93,22,'#292439cc');textAt('稍等一下，节拍等你 ♡',640,349,23,'#ffdeed','600','center');}}}finally{g=visible;}});}
function comicPanel(x,y,w,h,fill){roundRect(x+5,y+5,w,h,5,'#271b42');roundRect(x,y,w,h,5,fill);g.strokeStyle='#271b42';g.lineWidth=3;g.stroke();}
function drawRecordingHUD(){comicPanel(23,21,710,88,'#fff8e6');SevenComic.label(g,'七海快跑!!  /  '+(SevenWorlds.themes[settings.scene]?.name||'自定义背景'),44,51,19,'#fa459d','left');textAt([...chart.title].slice(0,37).join(''),44,82,16,'#4e2b67','600');comicPanel(754,21,294,88,'#fff035');SevenComic.label(g,String(engine?.score||0).padStart(7,'0'),774,60,31,'#fa429d','left');textAt(`${engine?.auto?'AUTO':practice?'练习':'SCORE'} · ${(engine?.accuracy??100).toFixed(2)}%`,774,86,14,'#462451','700');comicPanel(24,639,1227,60,'#fff8e7');const c=engine?.counts||{PERFECT:0,GOOD:0,MISS:0};textAt(`PERFECT ${c.PERFECT}   GOOD ${c.GOOD}   MISS ${c.MISS}   闪避 ${engine?.dodged||0}`,44,665,15,'#492456','700');textAt(timeText(clockTime())+' / '+timeText(duration()),1225,665,14,'#492456','700','right');roundRect(44,680,1183,6,2,'#d8c6dd');roundRect(44,680,Math.max(1,1183*clamp(clockTime()/duration(),0,1)),6,2,'#fa409d');}
function recordingReady(result){const preview=$('recordPreview');preview.pause();preview.src=result.url;$('recordResult').classList.remove('hidden');$('recordDetails').textContent=`${timeText(result.seconds)} · 1280 × 720 · 目标 ${result.options.fps} fps · ${(result.blob.size/1024/1024).toFixed(1)} MB · ${result.options.includeUI?'保留游戏 UI':'纯游戏画面'} · 含游戏音频`;$('recordDownload').href=result.url;$('recordDownload').download=`SevenBeat-${chart.title.replace(/[\\/:*?"<>|]/g,'_').slice(0,45)}-${new Date().toISOString().replace(/[:.]/g,'-')}.mp4`;toast('MP4 已生成，可预览并点击「下载 MP4」保存。');}
async function startRecording(){try{menuMusic.stop();if(!bootReady)throw new Error('音频与字体还在准备，请稍等。');await ensureContext().resume();$('recordPreview').pause();$('recordResult').classList.add('hidden');const started=await recording.start(recordAudio.stream,{includeUI:$('recordUI').checked,fps:Number($('recordFPS').value)});if(!started)return;lastRecordingFrame=0;paintRecording(performance.now(),true);if(status==='paused')await resumeGame();else if(status!=='playing')await startGame();if(status!=='playing')recording.stop();}catch(e){toast(e.message);}}
const skinLabels={background:'循环背景',upperNote:'空中怪兽',lowerNote:'地面怪兽',obstacle:'滚动齿轮',holdNote:'长按头部',run:'跑步 / 待机',upper:'空中 PERFECT',lower:'地面 PERFECT',hold:'长按 / 冲刺',good:'GOOD / 挥刀',miss:'MISS / 受击',upslash:'上撩',downslash:'下劈'};
function assetScale(key){const value=Number(settings.skinScales[key]);return clamp(Number.isFinite(value)?value:1,key==='background'?1:.5,1.6);}
const assetEditor=new SevenAssetEditor.AssetEditor({getAsset:key=>customSkins[key]||imageURL(images[key])||A.skins[{upperNote:'upper',lowerNote:'lower',holdNote:'hold'}[key]],getScale:assetScale,onOpen:()=>{if(status==='playing')pauseGame();},onApply:async(key,data,scale)=>{customSkins[key]=data;settings.skinScales[key]=scale;if(key==='background')settings.customBackground=true;saveSettings();await reloadAllSkins();refreshSkinSlots();refreshWorldSettings();try{await persist('skins',customSkins);toast('贴图与大小已应用并保存到本机。');}catch{toast('贴图已应用，但浏览器不允许持久保存。');}}});
async function loadDecorations(){await Promise.all(Object.entries(A.decorations).map(async([key,url])=>{const original=cutWhite(await loadImage(url)),c=document.createElement('canvas');c.width=384;c.height=Math.round(384*original.height/original.width);c.getContext('2d').drawImage(original,0,0,c.width,c.height);decorImages[key]=c;}));document.querySelectorAll('[data-decor]').forEach(el=>{el.src=imageURL(decorImages[el.dataset.decor]);el.draggable=false;});}
const menuMusic=new SevenMenuMusic(A.menuTracks,updateMenuHUD);
function menuAllowed(){const preview=$('recordPreview');return bootReady&&status==='ready'&&view!=='editor'&&!clockRunning&&!calibration&&!recording.active&&recording.state!=='stopping'&&(preview.paused||preview.ended)&&!document.hidden;}
let menuStamp='';
function syncMenuMusic(){const state={key:settings.menuSong,volume:settings.menuVolume,enabled:settings.menuEnabled,allowed:menuAllowed()},stamp=JSON.stringify(state);if(stamp!==menuStamp){menuStamp=stamp;menuMusic.configure(state);}updateMenuHUD();}
function updateMenuHUD(){const el=$('menuStatus');if(!el)return;const label=!settings.menuEnabled?'主页音乐已关闭':menuMusic?.failed?'音频无法播放，请重新选择歌曲':menuMusic?.playing?'正在循环播放':menuMusic?.blocked?'浏览器等待点击页面；也可关闭主页音乐':!menuAllowed()?'游玩 / 试听期间已停止':'音乐准备中…';if(el.textContent!==label)el.textContent=label;document.querySelector('.menu-player')?.classList.toggle('is-playing',!!menuMusic?.playing);const toggle=$('menuPlay');toggle.textContent=settings.menuEnabled?'♫ 关闭主页 BGM':'♪ 开启主页 BGM';toggle.setAttribute('aria-pressed',String(settings.menuEnabled));}
function buildMenuSettings(){for(const id of ['menuTrack','menuTrackSetting']){const select=$(id);select.replaceChildren();for(const[key,item]of Object.entries(A.menuTracks)){const opt=document.createElement('option');opt.value=key;opt.textContent=item.title;select.append(opt);}select.onchange=()=>{settings.menuSong=select.value;saveSettings();refreshMenuSettings();syncMenuMusic();menuMusic.unlock();};}for(const id of ['menuEnabled','menuEnabledSetting'])$(id).onchange=()=>{settings.menuEnabled=$(id).checked;saveSettings();refreshMenuSettings();syncMenuMusic();if(settings.menuEnabled)menuMusic.unlock();};$('menuVolume').oninput=()=>{settings.menuVolume=Number($('menuVolume').value);saveSettings();syncMenuMusic();};$('menuPlay').onclick=()=>{settings.menuEnabled=!settings.menuEnabled;saveSettings();refreshMenuSettings();syncMenuMusic();menuMusic.unlock();};}
function refreshMenuSettings(){for(const id of ['menuTrack','menuTrackSetting'])$(id).value=A.menuTracks[settings.menuSong]?settings.menuSong:'sympathy';for(const id of ['menuEnabled','menuEnabledSetting'])$(id).checked=settings.menuEnabled;$('menuVolume').value=clamp(Number(settings.menuVolume)||0,0,100);menuStamp='';syncMenuMusic();}
function buildColorSettings(){const list=$('colorMappings');list.replaceChildren();for(const[key,palette]of Object.entries(SevenColors.palettes)){const card=document.createElement('label');card.className='color-mapping';card.style.setProperty('--note-color',palette.main);const img=document.createElement('img');img.alt=palette.name;img.dataset.colorPreview=key;const title=document.createElement('span');title.textContent=palette.name;const select=document.createElement('select');select.dataset.colorShape=key;select.setAttribute('aria-label',palette.name+'对应图案');for(const[shape,label]of Object.entries(SevenColors.shapes)){const o=document.createElement('option');o.value=shape;o.textContent=label;select.append(o);}select.onchange=()=>{settings.colorShapes[key]=select.value;saveSettings();refreshColorSettings();};card.append(img,title,select);list.append(card);}for(const [id,lane]of [['fallbackUpperColor',0],['fallbackLowerColor',1]]){for(const[key,palette]of Object.entries(SevenColors.palettes)){const o=document.createElement('option');o.value=key;o.textContent=palette.name;$(id).append(o);}$(id).onchange=()=>{settings.laneColors[lane]=$(id).value;saveSettings();};}}
function refreshColorSettings(){document.querySelectorAll('[data-color-shape]').forEach(el=>{const color=el.dataset.colorShape,key=SevenColors.shapes[settings.colorShapes[color]]?settings.colorShapes[color]:SevenColors.defaults[color];el.value=key;document.querySelector(`[data-color-preview="${color}"]`).src=imageURL(colorSprites[color+':'+key]);});$('fallbackUpperColor').value=settings.laneColors[0];$('fallbackLowerColor').value=settings.laneColors[1];}
document.addEventListener('pointerdown',()=>menuMusic.unlock());document.addEventListener('keydown',()=>menuMusic.unlock());
// UI wiring
$('recordStart').onclick=startRecording;$('recordStop').onclick=()=>{recording.stop();if(status==='playing')pauseGame();};$('closeRecordPreview').onclick=()=>{$('recordPreview').pause();$('recordResult').classList.add('hidden');};$('recordPreview').onplay=()=>{if(status==='playing')pauseGame();};
for(const id of['elastic','ambientAmount'])$(id).oninput=()=>{settings[id]=Number($(id).value);saveSettings();refreshWorldSettings();};$('ambient').onchange=()=>{settings.ambient=$('ambient').value;saveSettings();};$('ambientEnabled').onchange=()=>{settings.ambientEnabled=$('ambientEnabled').checked;saveSettings();};$('useCustomBackground').onclick=()=>{settings.customBackground=true;saveSettings();refreshWorldSettings();};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelector('.brand').onclick=e=>{e.preventDefault();switchView('play');};$('startOverlay').onclick=()=>startGame();$('playPause').onclick=()=>status==='playing'?pauseGame():status==='paused'?resumeGame():startGame();$('restart').onclick=()=>startGame(practiceStart);$('backHome').onclick=exitGame;$('editCurrent').onclick=()=>switchView('editor');$('fullscreen').onclick=async()=>{const shell=document.querySelector('.stage-shell');if(shell.classList.contains('touch-fullscreen')){shell.classList.remove('touch-fullscreen');document.body.classList.remove('stage-expanded');placeTouchTargets();return;}try{if(document.fullscreenElement)await document.exitFullscreen();else if(shell.requestFullscreen)await shell.requestFullscreen();else throw new Error('fallback');}catch{shell.classList.add('touch-fullscreen');document.body.classList.add('stage-expanded');placeTouchTargets();}};
// A pointer remains on the lane where it started until release/cancel; multitouch
// and keyboard share ownership so one finger cannot release another held input.
for(const[id,lane]of[['upperPad',0],['lowerPad',1],['upperTarget',0],['lowerTarget',1]]){const b=$(id);b.oncontextmenu=e=>e.preventDefault();b.onpointerdown=e=>{if(e.button!==0||status!=='playing'||engine.auto)return;e.preventDefault();b.setPointerCapture(e.pointerId);activePointers.set(e.pointerId,lane);b.classList.add('is-down');hit(lane);};const up=e=>{if(!activePointers.has(e.pointerId))return;activePointers.delete(e.pointerId);b.classList.remove('is-down');if(![...activePointers.values()].includes(lane)&&!physicalKeys.has(settings.keys[lane]))release(lane);};b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;}
function placeTouchTargets(){const r=game.getBoundingClientRect(),shell=game.parentElement,s=shell.getBoundingClientRect();const scale=Math.min(r.width/1280,r.height/720),x=r.left-s.left-shell.clientLeft+(r.width-1280*scale)/2,y=r.top-s.top-shell.clientTop+(r.height-720*scale)/2;for(const[id,cy]of[['upperTarget',285],['lowerTarget',475]]){const b=$(id);const size=Math.max(44,154*scale);b.style.left=(x+330*scale)+'px';b.style.top=(y+cy*scale)+'px';b.style.width=b.style.height=size+'px';}}
new ResizeObserver(placeTouchTargets).observe(game);document.addEventListener('fullscreenchange',placeTouchTargets);
$('stagePause').onclick=()=>status==='playing'?pauseGame():status==='paused'?resumeGame():startGame();
document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{const key=$('builtinChart').value.replace(/_easy$/,'');loadBuiltIn(key+(b.dataset.difficulty==='easy'?'_easy':''));});
$('autoplay').onchange=()=>{if(engine&&(status==='playing'||status==='paused')){pauseGame();toast('自动演示模式将在重来后生效。');}};
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;document.querySelectorAll('[data-tool]').forEach(el=>el.classList.toggle('selected',el===b));});$('zoom').oninput=e=>zoom=Number(e.target.value);$('timelineScroll').oninput=e=>scroll=Number(e.target.value);$('undo').onclick=undo;$('redo').onclick=redo;
for(const[id,key]of[['chartTitle','title'],['bpm','bpm'],['chartOffset','offset']])$(id).onchange=()=>{checkpoint();chart[key]=key==='title'?$(id).value:Number($(id).value);try{chart=validateChart(chart);changed();syncEditor();}catch(e){undo();toast(e.message);}};
$('applyNote').onclick=()=>{const n=chart.notes.find(n=>n.id===selected);if(!n)return;const proposal=copy(chart),target=proposal.notes.find(n=>n.id===selected);target.time=Number($('noteTime').value);target.lane=Number($('noteLane').value);target.type=$('noteType').value;target.duration=target.type==='hold'?Number($('noteDuration').value):0;target.skin=$('noteSkin').value;target.color=$('noteColor').value;if(target.type==='dodge'){target.lane=1;target.duration=0;target.skin='obstacle';}else if(target.skin==='obstacle'){target.type='dodge';target.lane=1;target.duration=0;}try{const c=validateChart(proposal);checkpoint();chart=c;changed();updateInspector();}catch(e){toast(e.message);}};$('deleteNote').onclick=deleteSelected;$('noteType').onchange=()=>{if($('noteType').value==='dodge'){$('noteLane').value='1';$('noteSkin').value='obstacle';$('noteDuration').value='0';}else if($('noteSkin').value==='obstacle')$('noteSkin').value='monster';if($('noteType').value==='hold'&&Number($('noteDuration').value)<.08)$('noteDuration').value=.3;};
$('previewAudio').onclick=async()=>{try{if(clockRunning)stopClock();else await startClock(clamp(position,0,duration()-.001));}catch(e){toast(e.message);}};$('previewStop').onclick=()=>{stopClock();position=0;scroll=0;$('timelineScroll').value=0;noteRecording=[null,null];};
$('testChart').onclick=()=>{try{safeChart();switchView('play');startGame();}catch(e){toast(e.message);}};$('testFromHere').onclick=()=>{try{safeChart();const at=Math.max(0,clockTime());switchView('play');startGame(at);}catch(e){toast(e.message);}};
$('exportChart').onclick=exportChart;$('saveProject').onclick=saveProject;$('importAudio').onclick=()=>$('audioFile').click();$('importChart').onclick=()=>$('chartFile').click();
$('newChart').onclick=()=>{checkpoint();stopClock();chart={version:1,title:'我的新谱面',artist:'我的创作',bpm:120,offset:0,audio:audioName,duration:duration(),notes:[]};selected=null;position=0;scroll=0;changed();syncEditor();toast('已新建空白谱面；可导入自己的歌曲。原谱面可撤销恢复。');};
$('loadPractice').onclick=()=>loadBuiltIn('sugarbell');$('loadBuiltIn').onclick=()=>loadBuiltIn($('builtinChart').value);
document.querySelectorAll('[data-song]').forEach(b=>b.onclick=()=>loadBuiltIn(b.dataset.song+($('difficultyBar').querySelector('[data-difficulty=easy]').classList.contains('selected')&&A.examples[b.dataset.song+'_easy']?'_easy':'')));
$('audioFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>100*1024*1024){toast('请选择 100 MB 以内的音频文件。');return;}stopClock();try{const data=await fileData(file);await decodeAudio(data);audioData=data;audioName=file.name;chart.audio=file.name;chart.duration=duration();position=0;dirty=true;syncEditor();toast('歌曲已导入，现有音符保留，可继续编排。');}catch(e){toast('无法解码音频，请尝试 MP3、WAV 或 M4A。');}};
$('chartFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>150*1024*1024){toast('谱面文件过大。');return;}try{const obj=JSON.parse(await file.text()),c=validateChart(obj);if(obj.audioData&&!/^data:audio\/[\w.+-]+;base64,/.test(obj.audioData))throw new Error('内嵌音频格式无效。');stopClock();if(obj.audioData)await decodeAudio(obj.audioData);checkpoint();chart=c;selected=null;position=0;scroll=0;if(obj.audioData){audioData=obj.audioData;audioName=c.audio||'embedded-audio';}changed();syncEditor();toast(obj.audioData?'谱面与音乐已导入。':'谱面已导入；请导入与 audio 字段对应的歌曲。');}catch(e){toast('导入失败：'+e.message);}};
for(const[id,lane]of[['bindUpper',0],['bindLower',1]])$(id).onclick=()=>{bindLane=lane;$(id).textContent='请按键…';};
for(const id of['latency','speed','volume','sfxVolume','voiceVolume'])$(id).oninput=()=>{const ranges={latency:[-500,500],speed:[360,1050],volume:[0,100],sfxVolume:[0,100],voiceVolume:[0,100]};settings[id]=clamp(Number($(id).value)||0,...ranges[id]);if(id==='volume'||id==='voiceVolume')reactions?.volume();if(id==='sfxVolume'&&sfxGain)sfxGain.gain.value=settings.sfxVolume/100;saveSettings();};for(const id of['hitSound','effects','comboGlow','voiceEnabled'])$(id).onchange=()=>{settings[id]=$(id).checked;if(id==='voiceEnabled'){if(!settings.voiceEnabled)reactions?.stopVoice();else reactions?.volume();}saveSettings();};
$('calibrationTap').onpointerdown=e=>{e.preventDefault();calibrationTap();};$('calibrate').onclick=startCalibration;document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>{settings.palette=b.dataset.palette;saveSettings();refreshSettings();});$('resetSettings').onclick=()=>{settings=copy(defaults);saveSettings();refreshSettings();reactions?.volume();refreshSkinSlots();if(sfxGain)sfxGain.gain.value=settings.sfxVolume/100;toast('操作与显示设置已恢复默认。');};
$('resetSkins').onclick=async()=>{customSkins={};settings.skinScales={};saveSettings();await reloadAllSkins();refreshWorldSettings();try{await persist('skins',customSkins);}catch{}toast('已恢复原始七海动作与默认贴图。');};
$('skinFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(file)await assetEditor.importFile(file);};
async function reloadAllSkins(){await loadSkins();images.noteUpper=await loadImage(A.skins.upper);images.noteLower=await loadImage(A.skins.lower);images.noteHold=await loadImage(A.skins.hold);for(const key of['upperNote','lowerNote','holdNote'])if(customSkins[key])images[key]=await loadImage(customSkins[key]);}

window.addEventListener('keydown',e=>{const target=e.target,editing=/INPUT|SELECT|TEXTAREA|VIDEO/.test(target.tagName);if(target.closest?.('.project-notice')||$('assetEditor').open)return;if(bindLane!==null){e.preventDefault();if(e.code==='Escape'){bindLane=null;updateKeyLabels();return;}if(['Space','KeyR','Tab','Enter'].includes(e.code)||e.ctrlKey||e.altKey||e.metaKey||/^(Control|Alt|Shift|Meta)/.test(e.code)){toast('此键保留给界面操作，请选择其他按键。');return;}if(settings.keys[1-bindLane]===e.code){toast('上下轨不能使用同一按键。');return;}settings.keys[bindLane]=e.code;bindLane=null;saveSettings();updateKeyLabels();return;}
 if(calibration&&e.code==='Space'){e.preventDefault();if(e.repeat)return;calibrationTap();return;}
 if(editing)return;if(e.repeat)return;if(view==='play'){if(e.code==='Escape'||e.code==='Space'){e.preventDefault();if(status==='playing')pauseGame();else if(status==='paused')resumeGame();else startGame();return;}if(e.code==='KeyR'){e.preventDefault();startGame(practiceStart);return;}const lane=settings.keys.indexOf(e.code);if(lane>=0){e.preventDefault();physicalKeys.add(e.code);hit(lane);}}
 if(view==='editor'){if(e.code==='Space'){e.preventDefault();$('previewAudio').click();}if(e.ctrlKey&&e.code==='KeyZ'){e.preventDefault();e.shiftKey?redo():undo();}if(e.ctrlKey&&e.code==='KeyY'){e.preventDefault();redo();}if(e.code==='Delete'||e.code==='Backspace'){e.preventDefault();deleteSelected();}const lane=settings.keys.indexOf(e.code);if(lane>=0&&$('recordNotes').checked&&clockRunning){e.preventDefault();if(!noteRecording[lane])noteRecording[lane]={time:editorSnap(clockTime()-chart.offset),start:clockTime()};}}});
window.addEventListener('keyup',e=>{const lane=settings.keys.indexOf(e.code);if(lane<0)return;physicalKeys.delete(e.code);if(view==='play'&&![...activePointers.values()].includes(lane))release(lane);if(view==='editor'&&noteRecording[lane]){const rec=noteRecording[lane],len=clockTime()-rec.start;checkpoint();addNote(rec.time,lane,len>.22?'hold':'tap',len>.22?Math.max(.08,editorSnap(rec.time+len)-rec.time):0);noteRecording[lane]=null;}});
window.addEventListener('blur',()=>{if(status==='playing')pauseGame();if(view==='editor'){stopClock();noteRecording=[null,null];}});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(status==='playing')pauseGame();if(view==='editor')stopClock();}});window.addEventListener('beforeunload',e=>{if(dirty||recording.active||recording.state==='stopping'){e.preventDefault();e.returnValue='';}});

function loop(now){for(let lane=0;lane<2;lane++)if(characterInput.autoReleaseAt[lane]&&now>=characterInput.autoReleaseAt[lane])releaseCharacter(lane);if(resumeUntil&&now>=resumeUntil){resumeUntil=0;clockRunning=true;syncDodgeInput();if(engine)for(const n of engine.notes)if(n.state==='holding'&&!engine.held[n.lane]&&!engine.auto)engine.finish(n,'MISS');}
 if(view==='play'){if(status==='playing'&&clockRunning){if(engine.auto){const near=engine.notes.find(n=>n.type==='dodge'&&n.state!=='done'&&n.time-songTime()>=0&&n.time-songTime()<.12);if(near)autoJump(now,now+(near.time-songTime())*1000+120);}engine.update(songTime());if(clockTime()>=duration())finishGame();}updateVisualMotion(now);drawScene(now);paintRecording(now);if(status==='finished'&&recording.active&&(!ending||now>=ending.until))recording.stop();if(now-lastHud>65){updateHUD();updateRecordingCounter();lastHud=now;}}
 if(view==='editor'){if(clockRunning&&clockTime()>=duration()){stopClock();position=duration();noteRecording=[null,null];}drawTimeline();}
 if(calibration){while(calibration.index<12&&calibration.first+calibration.index*.5<ctx.currentTime+.12){clickTone(0,Math.max(ctx.currentTime,calibration.first+calibration.index*.5),true);calibration.index++;}if(ctx.currentTime>calibration.end+.3)endCalibration();}
 syncMenuMusic();requestAnimationFrame(loop);}
async function boot(){try{await loadCuteFont();buildSceneChooser();try{customSkins=await recall('skins')||{};}catch{}await reloadAllSkins();colorSprites=await SevenColors.build(A.skins,loadImage);buildColorSettings();buildMenuSettings();$('coverCharacter').src=imageURL(images.run);try{const p=await recall('project');if(p&&!(['example.m4a','example_2.m4a'].includes(p.chart?.audio)&&['ぱぴぷぴぷぴぱ · Video Example','example_2 · 分轨节奏'].includes(p.chart?.title))){chart=validateChart(p.chart);audioData=p.audioData;audioName=p.audioName;$('saveStatus').textContent='已恢复本机保存的谱面';}}catch{}ensureContext();await Promise.all([decodeAudio(audioData),reactions.load(A.voices),loadDecorations()]);bootReady=true;syncSong();syncEditor();refreshSettings();updateHUD();updateRecordingState(recording.state);}catch(e){toast('初始化失败：'+e.message);}requestAnimationFrame(loop);}
boot();
// Public diagnostics used by the included test harness and optional developer console.
window.SevenBeat={get chart(){return chart;},get engine(){return engine;},get status(){return status;},get ready(){return bootReady;},get settings(){return settings;},get characterLane(){return characterLane();},get characterPose(){return characterPose();},get crossPose(){return crossPose();},get lesson(){return currentLesson();},get visualMotion(){return {...visualMotion};},get comboShining(){return comboShining();},get recording(){return recording;},get menuMusic(){return {playing:menuMusic.playing,key:menuMusic.key,enabled:menuMusic.enabled,blocked:menuMusic.blocked,allowed:menuMusic.allowed,time:menuMusic.audio.currentTime};},get noteAppearance(){return n=>({color:SevenColors.color(n,settings),shape:SevenColors.shape(n,settings)});},get fontLoaded(){return document.fonts.check('16px SevenCute');},get ending(){return ending?{...ending}:null;},get voiceKey(){return reactions?.lastVoice;},get voicePlaying(){return !!reactions?.voice;},get voiceDurations(){return Object.fromEntries(Object.entries(reactions?.buffers||{}).map(([k,v])=>[k,v.duration]));},get audioDuration(){return duration();},get clockTime(){return clockTime();},startGame,pauseGame,resumeGame,exitGame,switchView,validateChart};
