/* Per-slot bitmap sizing. All saved textures are rasterized and capped at four million pixels. */
(function(root){'use strict';const MAX_PIXELS=4000000,MAX_EDGE=4096,MAX_BYTES=12*1024*1024;
 const recommended=key=>key==='background'?[1920,1080]:['upperNote','lowerNote','holdNote','obstacle'].includes(key)?[256,256]:[768,768];
 function fit(w,h,maxW=MAX_EDGE,maxH=MAX_EDGE){const k=Math.min(1,maxW/w,maxH/h,Math.sqrt(MAX_PIXELS/(w*h)));return [Math.max(1,Math.floor(w*k)),Math.max(1,Math.floor(h*k))];}
 function valid(w,h){return Number.isInteger(w)&&Number.isInteger(h)&&w>=16&&h>=16&&w<=MAX_EDGE&&h<=MAX_EDGE&&w*h<=MAX_PIXELS;}
 const read=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('图片读取失败。'));r.readAsDataURL(file);});
 const image=url=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('图片无法解码，请换用 PNG / JPG / WebP。'));im.src=url;});
 class AssetEditor{
  constructor({getAsset,getScale,onApply,onOpen}){Object.assign(this,{getAsset,getScale,onApply,onOpen});this.el=document.getElementById('assetEditor');this.q=id=>document.getElementById(id);this.serial=0;this.draft=null;this.busy=false;
   this.q('assetChoose').onclick=()=>this.q('skinFile').click();this.q('assetCancel').onclick=()=>this.el.close();this.el.addEventListener('close',()=>{this.serial++;this.draft=null;});
   for(const dim of ['Width','Height'])this.q('asset'+dim).oninput=()=>{if(!this.draft)return;const value=Number(this.q('asset'+dim).value);if(this.q('assetAspect').checked&&Number.isFinite(value)){const other=dim==='Width'?'Height':'Width';this.q('asset'+other).value=Math.max(1,Math.round(dim==='Width'?value/this.draft.ratio:value*this.draft.ratio));}this.refresh();};
   this.q('assetAspect').onchange=()=>{if(this.draft&&this.q('assetAspect').checked)this.draft.ratio=Number(this.q('assetWidth').value)/Number(this.q('assetHeight').value);};this.q('assetScale').oninput=()=>this.refresh();
   this.q('assetRecommend').onclick=()=>{if(!this.draft)return;const [w,h]=recommended(this.draft.key);this.setSize(...fit(this.draft.image.width,this.draft.image.height,w,h));this.refresh();};
   this.q('assetFit').onclick=()=>{if(!this.draft)return;const w=Number(this.q('assetWidth').value),h=Number(this.q('assetHeight').value);if(w>0&&h>0){this.setSize(...fit(w,h));this.refresh();}};
   this.q('assetApply').onclick=()=>this.apply();
  }
  async open(key,label){this.onOpen();this.serial++;this.draft=null;this.busy=false;this.q('assetTitle').textContent=label+' · 贴图与大小';const rec=recommended(key);this.q('assetRecommendation').textContent=`推荐 ${rec[0]} × ${rec[1]} px · 保存上限 4,000,000 像素 · 单边最多 4096 px · 文件最多 12 MB`;
   this.key=key;this.q('assetScale').min=key==='background'?'100':'50';this.q('assetScale').value=Math.max(Number(this.q('assetScale').min),this.getScale(key)*100);this.q('assetAspect').checked=true;this.q('assetStatus').textContent='请选择图片；调整后点击「应用」。';this.q('assetApply').disabled=true;this.q('assetChoose').disabled=false;this.el.showModal();const current=this.getAsset(key);if(current)await this.setSource(current);else{this.q('assetWidth').value=rec[0];this.q('assetHeight').value=rec[1];this.preview();}}
  setSize(w,h){this.q('assetWidth').value=w;this.q('assetHeight').value=h;}
  async setSource(url){const token=++this.serial;this.q('assetApply').disabled=true;try{const im=await image(url);if(token!==this.serial||!this.el.open)return;if(im.width*im.height>25000000)throw new Error('原图超过 2500 万像素的导入安全上限，请先缩小原图。');const [w,h]=fit(im.width,im.height);this.draft={key:this.key,image:im,ratio:im.width/im.height};this.setSize(w,h);this.q('assetAspect').checked=true;this.refresh();}catch(e){if(token===this.serial){this.q('assetStatus').textContent=e.message;this.refresh(false);}}}
  async importFile(file){if(!this.el.open)return;const token=++this.serial;this.q('assetApply').disabled=true;if(file.size>MAX_BYTES){this.q('assetStatus').textContent='文件超过 12 MB，请先压缩或缩小图片。';this.refresh(false);return;}try{const url=await read(file);if(token!==this.serial||!this.el.open)return;await this.setSource(url);}catch(e){this.q('assetStatus').textContent=e.message;this.refresh(false);}}
  refresh(message=true){const w=Number(this.q('assetWidth').value),h=Number(this.q('assetHeight').value);this.q('assetScaleValue').textContent=this.q('assetScale').value+'%';this.q('assetApply').disabled=this.busy||!this.draft||!valid(w,h);if(message&&this.draft)this.q('assetStatus').textContent=valid(w,h)?`原图 ${this.draft.image.width} × ${this.draft.image.height} → 保存 ${w} × ${h}（${(w*h).toLocaleString()} 像素）`:'尺寸超限：宽高需为 16–4096 的整数，且乘积不能超过 4,000,000。';this.preview();}
  preview(){const canvas=this.q('assetPreview'),c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);for(let y=0;y<canvas.height;y+=20)for(let x=0;x<canvas.width;x+=20){c.fillStyle=(x/20+y/20)%2?'#eddfeb':'#fff8ef';c.fillRect(x,y,20,20);}if(!this.draft)return;const w=Number(this.q('assetWidth').value),h=Number(this.q('assetHeight').value);if(!(w>0&&h>0))return;const scale=Math.min((canvas.width-50)/w,(canvas.height-50)/h)*Number(this.q('assetScale').value)/100;c.imageSmoothingQuality='high';c.drawImage(this.draft.image,(canvas.width-w*scale)/2,(canvas.height-h*scale)/2,w*scale,h*scale);}
  async apply(){if(!this.draft||this.busy)return;const w=Number(this.q('assetWidth').value),h=Number(this.q('assetHeight').value);if(!valid(w,h))return;this.busy=true;const token=this.serial,draft=this.draft,scale=Number(this.q('assetScale').value)/100;this.q('assetChoose').disabled=true;this.refresh(false);this.q('assetStatus').textContent='正在生成贴图…';try{const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.imageSmoothingQuality='high';ctx.drawImage(draft.image,0,0,w,h);const blob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));if(!blob)throw new Error('图片无法转换；请检查 SVG 是否引用外部资源。');if(blob.size>MAX_BYTES)throw new Error('保存后的 PNG 超过 12 MB，请减小像素尺寸。');const data=await read(blob);if(token!==this.serial||!this.el.open)return;await this.onApply(draft.key,data,scale);if(token===this.serial)this.el.close();}catch(e){this.q('assetStatus').textContent=e.message;}finally{this.busy=false;this.q('assetChoose').disabled=false;this.refresh(false);}}
 }
 root.SevenAssetEditor={AssetEditor,fit,valid,recommended,MAX_PIXELS};if(typeof module!=='undefined')module.exports=root.SevenAssetEditor;
})(typeof window!=='undefined'?window:globalThis);
