/* Original comic graphics. Rendering never changes note arrival times or input states. */
(function(root){
 'use strict';
 const ink='#251d42',palettes={PERFECT:{fill:'#ffe531',accent:'#ff42a1',word:'PERFECT!!'},GOOD:{fill:'#46eaff',accent:'#8753fa',word:'GOOD!'},MISS:{fill:'#ff496c',accent:'#433774',word:'MISS…'},HOLD:{fill:'#c8ff50',accent:'#36c5ca',word:'HOLD →'}};
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 function hash(s){let n=0;for(const c of String(s))n=(n*31+c.charCodeAt(0))>>>0;return n;}
 function path(c,points){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();}
 function star(c,x,y,r,points=5,inner=.5,angle=-Math.PI/2){const ps=[];for(let i=0;i<points*2;i++){const a=angle+i*Math.PI/points,rr=i%2?r*inner:r;ps.push([x+Math.cos(a)*rr,y+Math.sin(a)*rr]);}path(c,ps);}
 function label(c,text,x,y,size,fill='#fff',align='center'){c.save();c.font=`900 ${size}px "SevenCute","Microsoft YaHei",sans-serif`;c.textAlign=align;c.lineJoin='round';c.strokeStyle=ink;c.lineWidth=size*.24;c.strokeText(text,x+2,y+3);c.strokeStyle='#fff';c.lineWidth=size*.12;c.strokeText(text,x,y);c.fillStyle=fill;c.fillText(text,x,y);c.restore();}
 function burst(c,x,y,w,h,fill,angle=0){c.save();c.translate(x,y);c.rotate(angle);const ps=[];for(let i=0;i<24;i++){const a=i*Math.PI/12,r=i%2?.72:1;ps.push([Math.cos(a)*w*.5*r,Math.sin(a)*h*.5*r]);}path(c,ps);c.fillStyle=ink;c.translate(5,6);c.fill();c.translate(-5,-6);c.fillStyle=fill;c.fill();c.strokeStyle=ink;c.lineWidth=3;c.stroke();c.restore();}
 function target(c,lane,y,t,key,held,impact,effects=true){const color=lane?'#ff53b7':'#29e3ef',age=impact?(performance.now()-impact.born)/650:2,active=age<1,pal=active?palettes[impact.grade]||palettes.PERFECT:null;const bounce=active&&effects?Math.sin(age*16)*Math.exp(-age*4)*.17:0;c.save();c.translate(330,y);if(active&&impact.grade==='MISS'&&effects)c.translate(Math.sin(age*58)*10*(1-age),0);c.scale(1+bounce,1+bounce);c.strokeStyle=ink;c.lineWidth=5;c.fillStyle='#ffffffb8';c.beginPath();c.arc(0,0,43,0,Math.PI*2);c.fill();c.stroke();c.strokeStyle=pal?pal.fill:color;c.lineWidth=8;c.beginPath();c.arc(0,0,37,0,Math.PI*2);c.stroke();c.save();c.rotate(t*.7*(lane?-1:1));for(let i=0;i<4;i++){c.rotate(Math.PI/2);path(c,[[0,-59],[7,-48],[-7,-48]]);c.fillStyle=color;c.fill();c.strokeStyle=ink;c.lineWidth=2;c.stroke();}c.restore();if(held){c.fillStyle=color+'88';c.beginPath();c.arc(0,0,29,0,Math.PI*2);c.fill();}label(c,key,0,8,22,pal?pal.fill:color);c.fillStyle=ink;c.font='bold 11px SevenCute';c.textAlign='center';c.fillText(lane?'LAND / 地面':'AIR / 空中',0,78);
 if(active&&effects){c.globalAlpha=1-age;if(impact.grade==='MISS'){c.strokeStyle='#ff315d';c.lineWidth=8;c.beginPath();c.moveTo(-34,-34);c.lineTo(34,34);c.moveTo(34,-34);c.lineTo(-34,34);c.stroke();}else{c.strokeStyle=pal.fill;c.lineWidth=7*(1-age)+1;c.beginPath();c.arc(0,0,48+age*72,0,Math.PI*2);c.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4,r=55+age*80;star(c,Math.cos(a)*r,Math.sin(a)*r,7*(1-age)+2,4);c.fillStyle=i%2?pal.fill:pal.accent;c.fill();}}}c.restore();}
 function note(c,n,x,y,t,sprite,elastic=true,visualScale=1){const seed=hash(n.id),power=clamp(Number(elastic),0,1),entry=clamp((1330-x)/230,0,1);const ease=1+2.70158*Math.pow(entry-1,3)+1.70158*Math.pow(entry-1,2);const calm=clamp(Math.abs(x-330)/230,0,1),bob=Math.sin(t*4.8+seed%23)*7*calm*power,squash=Math.sin(t*5.3+seed%17)*.045*calm*power;c.save();c.translate(x,y+bob-(1-entry)*25*power);c.rotate(Math.sin(t*3.8+seed%13)*.08*calm*power);const scale=1+power*(.25+.75*ease-1);c.scale(visualScale*scale*(1+squash),visualScale*scale*(1-squash));c.globalAlpha=.45+.55*entry;c.shadowColor=ink+'55';c.shadowOffsetY=6;if(sprite)c.drawImage(sprite,-46,-46,92,92);c.restore();}
 function gear(c,n,x,t,sprite,showHint=true,visualScale=1){c.save();c.translate(x,520);c.scale(visualScale,visualScale);c.fillStyle=ink+'30';c.beginPath();c.ellipse(0,49,45,9,0,0,Math.PI*2);c.fill();c.save();c.rotate(x/43);if(sprite)c.drawImage(sprite,-48,-48,96,96);c.restore();if(showHint){c.fillStyle='#ffed35';c.strokeStyle=ink;c.lineWidth=2;path(c,[[-24,-65],[15,-65],[25,-57],[15,-49],[-24,-49]]);c.fill();c.stroke();label(c,'跳!',-1,-52,15,'#ff3b98');}c.restore();}
 function feedback(c,j,now,showUI=true){const age=(now-j.born)/780;if(age<0||age>=1||!showUI)return;const p=palettes[j.grade]||palettes.HOLD,x=j.dodge?235:492,y=(j.lane?475:285)-94-age*28;c.save();c.globalAlpha=Math.min(1,(1-age)*2.6);c.translate(x,y);const pop=1+Math.sin(age*17)*Math.exp(-age*7)*.22;c.scale(pop,pop);const angle=j.grade==='MISS'?.12+Math.sin(age*32)*.03:-.07;c.rotate(angle);
 if(j.grade==='PERFECT'){burst(c,0,0,256,76,p.fill);star(c,-128,-25,20,5);c.fillStyle=p.accent;c.fill();c.strokeStyle=ink;c.lineWidth=3;c.stroke();}
 else if(j.grade==='MISS'){path(c,[[-111,-29],[102,-25],[111,21],[60,21],[45,41],[31,20],[-106,23],[-96,1]]);c.fillStyle=ink;c.fill();c.strokeStyle='#ff75ad';c.lineWidth=4;c.stroke();}
 else{c.fillStyle=p.accent;c.fillRect(-104,-27,220,64);path(c,[[-110,-33],[108,-26],[105,26],[-110,28],[-126,43],[-116,9]]);c.fillStyle=p.fill;c.fill();c.strokeStyle=ink;c.lineWidth=3;c.stroke();}
 label(c,j.dodge?(j.grade==='MISS'?'撞到了!':'DODGE!'):p.word,0,10,j.grade==='PERFECT'?29:31,j.grade==='MISS'?'#ff709d':p.accent);
 if(j.grade==='GOOD'){c.fillStyle=ink;c.font='bold 11px SevenCute';c.textAlign='center';c.fillText(`${j.error>0?'稍晚':'稍早'} ${Math.round(Math.abs(j.error)*1000)} ms`,0,44);}c.restore();}
 function impact(c,j,now){const a=(now-j.born)/520;if(a<0||a>=1)return;const p=palettes[j.grade]||palettes.HOLD,x=j.dodge?181:330,y=j.dodge?520:(j.lane?475:285);c.save();c.translate(x,y);c.globalAlpha=1-a;if(j.grade==='MISS'){c.strokeStyle='#ff3768';c.lineWidth=6;for(let i=0;i<7;i++){const angle=i*Math.PI*2/7;c.save();c.rotate(angle);path(c,[[26,0],[45+a*40,10],[39+a*58,-4],[68+a*40,7]]);c.stroke();c.restore();}c.fillStyle='#ff44792b';c.fillRect(-70,-70,140,140);}else{for(let i=0;i<10;i++){const angle=i*Math.PI/5+(j.grade==='GOOD'?.2:0),r=24+a*88;c.save();c.translate(Math.cos(angle)*r,Math.sin(angle)*r);c.rotate(a*3+i);star(c,0,0,(j.grade==='PERFECT'?13:9)*(1-a)+2,j.grade==='PERFECT'?5:4);c.fillStyle=i%2?p.fill:p.accent;c.fill();c.lineWidth=2;c.strokeStyle=ink;c.stroke();c.restore();}}c.restore();}
 root.SevenComic={hash,label,burst,target,note,gear,feedback,impact,palettes};
})(window);
