/* Outcome rules, independent character voices, and the FULL COMBO celebration. */
(function(root){'use strict';
 function outcome(counts,total,{practice=false,auto=false}={}){const judged=counts.PERFECT+counts.GOOD+counts.MISS,hits=counts.PERFECT+counts.GOOD;return {hitRate:judged?hits/judged*100:0,judged,fullCombo:total>0&&judged===total&&counts.MISS===0&&!practice,auto,practice};}
 function chooseVoice(rate,random=Math.random){if(random()<.001)return 'easter';return `${rate>80?'praise':rate>=60?'encourage':'taunt'}-${random()<.5?1:2}`;}
 class AudioReactions{
  constructor(ctx,music,mix,sfx,settings){this.ctx=ctx;this.music=music;this.sfx=sfx;this.settings=settings;this.voiceGain=ctx.createGain();this.voiceGain.connect(mix);this.buffers={};this.voice=null;this.nodes=new Set();this.lastVoice=null;}
  async load(assets){await Promise.all(Object.entries(assets).map(async([key,uri])=>{const s=atob(uri.split(',')[1]),bytes=Uint8Array.from(s,c=>c.charCodeAt(0));this.buffers[key]=await this.ctx.decodeAudioData(bytes.buffer);}));}
  volume(){const s=this.settings(),at=this.ctx.currentTime;this.voiceGain.gain.setValueAtTime((s.voiceEnabled?s.voiceVolume:0)/100,at);this.music.gain.cancelScheduledValues(at);this.music.gain.setTargetAtTime(s.volume/100*(this.voice&&s.voiceEnabled&&s.voiceVolume>0?.5:1),at,.045);}
  stopVoice(){const old=this.voice;this.voice=null;if(old){old.onended=null;try{old.stop();}catch{}old.disconnect();}this.volume();}
  play(key,delay=0){this.stopVoice();this.lastVoice=key;const s=this.settings(),buffer=this.buffers[key];if(!s.voiceEnabled||s.voiceVolume<=0||!buffer)return 0;const node=this.ctx.createBufferSource();node.buffer=buffer;node.connect(this.voiceGain);this.voice=node;this.volume();node.onended=()=>{if(this.voice===node){this.voice=null;this.volume();}node.disconnect();};node.start(this.ctx.currentTime+delay);return delay+buffer.duration;}
  celebrate(){const s=this.settings();if(!s.hitSound||s.sfxVolume<=0)return 0;const at=this.ctx.currentTime;const tone=(midi,start,dur,amp)=>{const o=this.ctx.createOscillator(),a=this.ctx.createGain();o.type='triangle';o.frequency.value=440*2**((midi-69)/12);a.gain.setValueAtTime(0,start);a.gain.linearRampToValueAtTime(amp,start+.012);a.gain.exponentialRampToValueAtTime(.0001,start+dur);o.connect(a);a.connect(this.sfx);this.nodes.add(o);o.onended=()=>{this.nodes.delete(o);o.disconnect();a.disconnect();};o.start(start);o.stop(start+dur+.02);};[60,64,67,72,76,79,84].forEach((m,i)=>tone(m,at+i*.09,.52,.085));[60,67,72,76].forEach(m=>tone(m,at+.74,1.05,.042));return 1.82;}
  stop(){this.stopVoice();for(const n of this.nodes)try{n.stop();}catch{}this.nodes.clear();}
 }
 function drawCelebration(c,state,now,{ui=true,effects=true}={}){if(!state?.fullCombo)return;const age=(now-state.born)/1000;c.save();if(effects&&age<5.5){const colors=['#ff49a8','#fff148','#30e4eb','#a886ff'];for(let i=0;i<100;i++){const seed=(i*2654435761)>>>0,phase=(age*.23+(seed%1000)/1000)%1,x=(seed%1280)+Math.sin(age*3+i)*35,y=-60+phase*860;c.save();c.translate(x,y);c.rotate(age*(i%2?2:-2)+i);c.fillStyle=colors[i%4];c.fillRect(-4,-7,8+(i%3)*2,13);c.restore();}}if(ui){const pop=age<.65?1+Math.sin(age*18)*Math.exp(-age*5)*.13:1;c.translate(640,312);c.scale(pop,pop);root.SevenComic.label(c,state.auto?'AUTO · FULL COMBO!':'FULL COMBO!',0,0,state.auto?65:82,'#fff04d');root.SevenComic.label(c,'零失误通关！',0,62,28,'#ff75c5');}c.restore();}
 root.SevenReactions={outcome,chooseVoice,AudioReactions,drawCelebration};if(typeof module!=='undefined')module.exports=root.SevenReactions;
})(typeof window!=='undefined'?window:globalThis);
